eureka:
  instance:
    prefer-ip-address: true #使用IP注册
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    ##续约更新时间间隔设置5秒，m默认30s
    lease-renewal-interval-in-seconds: 5
    ##续约到期时间10秒，默认是90秒
    lease-expiration-duration-in-seconds: 10
  client:
      service-url:
        defaultZone: http://192.168.1.241:9090/eureka/
server:
  port: 9411
spring:
  application:
    name: cloudplatform-zipkin
  zipkin:
  #关闭本地推送
    enabled: false
    sender:
      type: web
  datasource:
    schema: classpath:/mysql.sql
    url: jdbc:mysql://192.168.1.210:3306/test?zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2b8
    username: huiqing
    password: huiqing
    initialize: true
    continue-on-error: true
  sleuth:
    enabled: false
    sampler:
      percentage: 1.0
    #使用mysql存储策略
zipkin:
  storage:
    type: mysql
management:   #actuator  去除认证
  security:
    enabled: false
    
